# Generated by Django 6.0.7 on 2026-07-23 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0003_disponibilidadterapeuta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocion_objetivo', models.CharField(choices=[('FELIZ', 'Feliz / Motivado'), ('ANSIOSO', 'Ansioso / Preocupado'), ('TRISTE', 'Triste / Desanimado'), ('ESTRESADO', 'Estresado / Saturado'), ('NEUTRAL', 'Neutral / Tranquilo')], max_length=20)),
                ('intensidad', models.IntegerField(default=5, help_text='Nivel de intensidad de 1 a 10')),
                ('motivo_emocion', models.TextField(blank=True, help_text='Por qué se sentía así el paciente', null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'PACIENTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_emocionales_asignadas', to=settings.AUTH_USER_MODEL)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_emocionales_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
