# Generated by Django 6.0.7 on 2026-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalidad_app', '0011_reportecomportamientopaciente'),
    ]

    operations = [
       
    ]
